config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'

  get 'sessions/new'

  resources :users

  resources :restaurants

  get 'dashboard' => 'users#dashboard'

  post 'users/:id/role_change' => 'users#role_change'


  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'reserve' => 'reservations#new'
  post 'reserve' => 'reservations#create'
  delete 'reserve' => 'reservations#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :restaurants
	validates :name,:email, presence: true, uniqueness: true
	validates :password, presence: true

	include BCrypt

	def password
	  @password ||= BCrypt::Password.new(password_digest)
	end

	def password=(new_password)
	  @password = BCrypt::Password.create(new_password)
	  self.password_digest = @password
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :role_change]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def dashboard
    if logged_in?
      @user = current_user
    else
      flash[:alert] = "You must be logged in to view the dashboard."
      redirect_to login_path
    end
  end

  def role_change

    if @user == current_user
      if @user.role == 'patron'
        @user.role = 'owner'
        @user.save!
      elsif @user.role == 'owner'
        @user.role = 'patron'
        @user.save!
      end
      redirect_to user_path @user
    end

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.password = user_params[:password]

    respond_to do |format|
      if @user.save
        format.html { redirect_to :root, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        log_in @user
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_digest, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def patron?
    if logged_in?
      if current_user.role=='patron'
      	true
      end
    else
      false
    end
  end

  def owner?
    if logged_in?
      if current_user.role=='owner'
      	true
      end
    else
      false
    end
  end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  <% log_in @user %>
<% end %>

app/views/users/dashboard.html.erb
<h1>Dashboard</h1>

<% @restaurants = current_user.restaurants.all %>
<% @restaurants.each do |restaurant| %>
<p>----------------------------------------------------------------------------------</p>
<p>
  <strong>Name:</strong>
  <%= restaurant.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= restaurant.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= restaurant.address %>
</p>

<p>
  <strong>City:</strong>
  <%= restaurant.city %>
</p>

<p>
  <strong>State:</strong>
  <%= restaurant.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= restaurant.zipcode %>
</p>

<p>
  <strong>Phone:</strong>
  <%= restaurant.phone %>
</p>

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
	<strong>Role:</strong>
	<%= @user.role %>
</p>
<p>
	Change Your Role:
	<%= form_tag "#{params[:id]}/role_change", method: "post" do %> 
		<button value="role_change">Change Role</button>
	<% end %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', restaurants_path %>