config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'

  get 'sessions/new'

  resources :users

  resources :restaurants

  get 'dashboard' => 'users#dashboard'

  post 'users/:id/role_change' => 'users#role_change'


  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'reserve' => 'reservations#new'
  post 'reserve' => 'reservations#create'
  delete 'reserve' => 'reservations#destroy'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	belongs_to :user
	has_many :reservations
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	before_action :require_login, only: [:new,:create]
	before_action :require_current_user, only: [:update,:edit,:destroy, :delete]

	def new
		@restaurant = Restaurant.new
	end

	def index
		@restaurants = Restaurant.all
	end

	def create
		@owner = current_user
		@restaurant = @owner.restaurants.create(restaurant_params)

		if @restaurant.save
			redirect_to @restaurant
		else
			render 'new'
		end
	end

	def show
		@restaurant = Restaurant.find(params[:id])
		@owner = @restaurant.user
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		@restaurant = Restaurant.find(params[:id])

		if @restaurant.update(restaurant_params)
			redirect_to @restaurant
		else
			render 'edit'
		end
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy

		redirect_to restaurants_path
	end

	private
	def restaurant_params
		params.require(:restaurant).permit(:name,:description,:address, :city, :zipcode, :state, :phone)
	end

	def require_login
		unless logged_in?
			flash[:alert] = "You must be logged in to perform this action."
			redirect_to login_path
		end
	end
	def require_current_user
		@restaurant = Restaurant.find(params[:id])
		unless current_user == @restaurant.user
			flash[:alert] = "You must be the restaurant's owner to perform this action."
			if !logged_in?
				redirect_to login_path
			end
		end
	end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>

  <p>
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </p>

  <p>
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </p>

  <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/restaurants/edit.html.erb
<% if current_user == @owner %>
<h1>Edit the Restaurant Info</h1>

<%= render 'form' %>
<% else %>
<% flash[:alert] = "You must be the restaurant's owner to perform this action." %>
<% redirect_to :root %>
<% end %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>

<table>
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Address</th>
		<th>City</th>
		<th>State</th>
		<th>Zipcode</th>
		<th>Phone</th>
	</tr>

	<% @restaurants.each do |restaurant| %>
	<tr>
		<td><%= restaurant.name %></td>
		<td><%= restaurant.description %></td>
		<td><%= restaurant.address %></td>
		<td><%= restaurant.city %></td>
		<td><%= restaurant.state %></td>
		<td><%= restaurant.zipcode %></td>
		<td><%= restaurant.phone %></td>
		<td><%= link_to 'Show', restaurant_path(restaurant) %></td>
	</tr>
	<% end %>
</table>

<%= link_to 'New Restaurant', new_restaurant_path %>

<% restaurants_locations = "" %>
<% @restaurants.each do |restaurant| %>
<% if restaurant == @restaurants[0] %>
<% restaurants_locations +="#{restaurant.address.gsub(" ","+")}+#{restaurant.city}+#{restaurant.state}" %>
<% else %>
<% restaurants_locations +="|#{restaurant.address.gsub(" ","+")}+#{restaurant.city}+#{restaurant.state}" %>
<% end %>
<% end %>

<p><img src="https://maps.googleapis.com/maps/api/staticmap?size=400x400&markers=<%= restaurants_locations %>&key=AIzaSyBwzq71n1sEb3jFlUFPesxYNBIuR3Zqw4g"></p>

app/views/restaurants/new.html.erb
<% if logged_in? %>
<h1>Create a New Restaurant</h1>

<%= render 'form' %>
<% else %>
<% redirect_to login_path %>
<% end %>

app/views/restaurants/show.html.erb
<p>
  <strong>Owner:</strong>
  <%= @owner.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @restaurant.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @restaurant.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @restaurant.zipcode %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @restaurant.phone %>
</p>

<% unless owner? %>
<%= render 'reservations/form' %>
<% else %>
<% @reservations = @restaurant.reservations.all %>
<table>
  <tr>
    <th>Email</th>
    <th>Date</th>
    <th>Time</th>
  </tr>

  <% @reservations.each do |reservation| %>
  <tr>
    <td><%= reservation.email %></td>
    <td><%= reservation.date %></td>
    <td><%= reservation.time %></td>
    <td><%= link_to 'Confirm', reserve_path(reservation), method: :delete %></td>
  </tr>
  <% end %>
</table>
<% end %>

<%= link_to 'Back', restaurants_path %> | <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> | <%= link_to 'Delete', restaurant_path(@restaurant), method: :delete %>

<% restaurant_location = "#{@restaurant.address.gsub(" ","+")}+#{@restaurant.city}+#{@restaurant.state}" %>

<p><img src="https://maps.googleapis.com/maps/api/staticmap?size=400x400&markers=<%= restaurant_location %>&key=AIzaSyBwzq71n1sEb3jFlUFPesxYNBIuR3Zqw4g"></p>