config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'

  get 'sessions/new'

  resources :users

  resources :restaurants

  get 'dashboard' => 'users#dashboard'

  post 'users/:id/role_change' => 'users#role_change'


  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'reserve' => 'reservations#new'
  post 'reserve' => 'reservations#create'
  delete 'reserve' => 'reservations#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reservester</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% flash.each do |type, message| %>
	  <div class="alert <%= bootstrap_class_for(type) %> fade in">
	    <button class="close" data-dismiss="alert">×</button>
	    <%= message %>
	  </div>
	<% end %>

	<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Reservester</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      	<% if logged_in? %>
      		<li><p class="navbar-text">Signed in as <%= @current_user.name %></p></li>
          <li><%= link_to("Dashboard", dashboard_path) %></li>
      		<li><%= link_to "Log out", logout_path, method: :delete %></li>
      	<% else %>
	        <li><a href="/login">Login</a></li>
	        <li><a href="users/new">Signup</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>